DROP SEQUENCE NOTICEBOARDSEQ;
DROP TABLE NOTICEBOARD;

CREATE SEQUENCE NOTICEBOARDSEQ;


CREATE TABLE NOTICEBOARD(
	NOTICEBOARDSEQ NUMBER PRIMARY KEY NOT NULL,
	BOARDKIND NUMBER NOT NULL,
	NOTICEDATE DATE NOT NULL,
	NOTICETITLE VARCHAR2(200),
	NOTICECONTENT VARCHAR2(4000), 
	USERID VARCHAR2(30) NOT NULL,
	USERSEQ NUMBER NOT NULL,
	NOTICEIMG VARCHAR2(4000)
);

SELECT * FROM NOTICEBOARD;

INSERT INTO NOTICEBOARD
VALUES (NOTICEBOARDSEQ.NEXTVAL, 3, SYSDATE, '작성자', '작스엉자', 'cj', 2, NULL);

