DROP SEQUENCE USERSEQ;
DROP TABLE USERS;


CREATE SEQUENCE USERSEQ;

CREATE TABLE USERS(
	USERSEQ NUMBER PRIMARY KEY,
	USERID VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(100) NOT NULL,
	USEREMAIL VARCHAR2(1000) NOT NULL,
	USERPHONE VARCHAR2(1000) NOT NULL,
	USEROADDRESS VARCHAR2(4000) NOT NULL,
	USERADDRESS VARCHAR2(4000) NOT NULL,
	USERDETAILADDRESS VARCHAR2(4000) NOT NULL,
	USERROLE VARCHAR2(100) CHECK(USERROLE IN ('admin', 'user')),
	USERNAME VARCHAR2(100) NOT NULL,
	USERBIRTHDAY VARCHAR2(100) NOT NULL
);

SELECT * FROM USERS;

DELETE FROM USERS WHERE USERID = 'kim1234';


SELECT * FROM PRODUCT;
