DROP SEQUENCE USERSEQ;
DROP TABLE USERS;


CREATE SEQUENCE USERSEQ;

CREATE TABLE USERS(
	USERSEQ NUMBER PRIMARY KEY,
	USERID VARCHAR2(100) NOT NULL,
	PASSWORD VARCHAR2(100) NOT NULL,
	USEREMAIL VARCHAR2(1000) NOT NULL,
	USERPHONE VARCHAR2(1000) NOT NULL,
	USEROADDRESS VARCHAR2(4000) NOT NULL,
	USERADDRESS VARCHAR2(4000) NOT NULL,
	USERDETAILADDRESS VARCHAR2(4000) NOT NULL,
	USERROLE VARCHAR2(100) CHECK(USERROLE IN ('admin', 'user')),
	USERNAME VARCHAR2(100) NOT NULL,
	USERBIRTHDAY VARCHAR2(100) NOT NULL
);


ALTER TABLE USERS ADD UNIQUE (USERID);

SELECT * FROM USERS;

DELETE FROM USERS WHERE USERID = 'kim1234';


SELECT * FROM PRODUCT;



DROP TABLE CHATROOM;
DROP TABLE MESSAGE;

DROP SEQUENCE MESSAGE_ID;
DROP SEQUENCE CHATROOM_ID;

CREATE SEQUENCE MESSAGE_ID;
CREATE SEQUENCE CHATROOM_ID;


CREATE TABLE MESSAGE (
   MESSAGE_ID NUMBER PRIMARY KEY,
   MESSAGE_SENDER VARCHAR2(45) NOT NULL,
   MESSAGE_RECEIVER VARCHAR2(45) NOT NULL,
   MESSAGE_CONTENT VARCHAR2(4000) NOT NULL,
   MESSAGE_REGDATE DATE DEFAULT CURRENT_TIMESTAMP NOT NULL,
   CHATROOM_ID NUMBER,
   CONSTRAINT FK_CHATROOM_ID FOREIGN KEY(CHATROOM_ID) REFERENCES CHATROOM (CHATROOM_ID)
);

CREATE TABLE CHATROOM ( 
   CHATROOM_ID NUMBER PRIMARY KEY,
   CREATE_CHATROOM_USER VARCHAR2(100) NOT NULL,
   CHATROOM_REGDATE DATE NOT NULL,
   CONSTRAINT FK_CREATE_CHATROOM_USER FOREIGN KEY(CREATE_CHATROOM_USER) REFERENCES USERS (USERID)
);

ALTER TABLE CHATROOM ADD CHATROOM_TITLE VARCHAR2(100) NOT NULL;
ALTER TABLE CHATROOM ADD CHATROOM_SELLER VARCHAR2(100) NOT NULL;
ALTER TABLE CHATROOM RENAME COLUMN CREATE_CHATROOM_USER TO CHATROOM_BUYER;
ALTER TABLE MESSAGE MODIFY MESSAGE_REGDATE DATE NOT NULL;


SELECT * FROM MESSAGE;
SELECT * FROM CHATROOM;

DELETE FROM CHATROOM WHERE chatroom_id = '39';
DELETE FROM MESSAGE WHERE CHATROOM_ID = '35';
DELETE FROM CHATROOM WHERE chatroom_id = '25';
UPDATE MESSAGE SET message_id = '2' WHERE message_id = '1';

INSERT INTO CHATROOM VALUES(chatroom_id.NEXTVAL, 'ddd', SYSDATE);
INSERT INTO MESSAGE VALUES(message_id.NEXTVAL, 'kim1234', 'dohan123', '제가 사고 싶어요 살 수 있을까요?', 
current_timestamp, '34');



SELECT * FROM CHATROOM WHERE CHATROOM_TITLE = '당근하나';




